version: '3.5'
services:
  db:
    image: mysql:5.5
    container_name: db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/app
    environment:
      MYSQL_ROOT_PASSWORD:
      DATABASE_HOST: mysql
      DATABASE_USER_NAME: root
      DATABASE_PASSWORD:
  web:
    build: .
    container_name: app
    command: bundle exec rails s -p 5050 -b '0.0.0.0'
    volumes:
      - .:/app
      - web_rubygems:/usr/local/bundle
    ports:
      - "5050:5050"
    depends_on:
      - db
    tty: true 
    stdin_open: true
volumes:
  db_data:
  web_rubygems:
