version: '3.5'
services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    env_file: .env
  web:
    build: .
    container_name: web
    command: bundle exec rails s -p 5050 -b '0.0.0.0'
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
      DB_HOST: db
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    tty: true
    stdin_open: true
volumes:
  db_data:
  web_rubygems:
