default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER") || "root" %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") || "root" %>
  host:  <%= ENV.fetch("MYSQL_HOST") || "localhost" %>
  port: 3306
  timeout: 5000

development:
  <<: *default
  database: test_app_development
test:
  <<: *default
  database: test_app_test
production:
  <<: *default
  database: test_app_prod
