# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: "root"
  password:
  host: localhost
  port: 3306
  timeout: 5000

development:
  <<: *default
  database: test_app_development
test:
  <<: *default
  database: test_app_test
production:
  <<: *default
  database: test_app_prod
